---
- hosts: all
  remote_user: root
  gather_facts: False
  vars_files:
    - vars/all.yml
  roles:
    - compatibility   # installs python2 on ubuntu 16 that way ansible will actually work
    - base
    - user
    - ssh
    - nginx
