- name: Locking down SSH user login
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config.test owner=root group=root mode="u=rw,g=r,o=r"

- name: Restart SSH service
  service: name=ssh state=restarted

- name: Allow SSH Port through UFW
  ufw: rule=allow port={{ ssh.port }}

- name: Make sure UFW is enabled after allowing the port
  ufw: state=enabled