- name: Setup User Account
  user: name={{ users.username }} password={{ users.password }} comment="System"

- name: Create User SSH Folder
  file: path=/home/{{ users.username }}/.ssh state=directory owner={{ users.username }} mode=0700

- name: Copy Public Key to Remote
  authorized_key: user={{ users.username }} key=" {{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }} "

- name: Locking down SSH user login
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config.test owner=root group=root mode="u=rw,g=r,o=r"

- name: Restart SSH service
  service: name=ssh state=restarted

- name: Allow SSH Port through UFW
  ufw: rule=allow port={{ users.ssh_port }}

- name: Make sure UFW is enabled after allowing the port
  ufw: state=enabled