- name: Apt-Get Update
  apt: update_cache=yes

- name: Upgrade System
  apt: upgrade=dist

- name: Install Fail2Ban
  apt: pkg="fail2ban" state=latest

- name: Install Ubuntu UncomplicatedFirewall (UFW)
  apt: pkg="ufw" state=latest